### ISSUE TITLE
[Bug Report] Blocks don't drop, even with Silk Touch

### ISSUE THREAD

**Issue by Delfite** [Cheaterpaul/EnchantmentMachine#10]
Description:
When attempting to break the Enchanter, Disenchanter, or the Enchantment Block with any tool (including things like hoes, axes, pickaxes, etc.) the blocks will take a very long time to break and once broken will never drop the actual block as stated in the title of this report. Mods that display block and entity info such as The One Probe, say that the blocks do not require ANY tool in order to break (I'm assuming that's why it never drops the actual block).

Minecraft Version: 1.17.1
Forge Version: 37.0.75
Mod Version: EnchantmentMachine-1.17.1-1.0.5.jar
Verified with: The One Probe

Note: Using CTRL+Middle-Click to select the blocks in creative mode shows that they have their NBT data saved, but their tooltips still say 0 enchantments stored. Removing any enchantment from either block results in the enchantment staying there. Example: If I remove the single Efficiency 4 enchantment I have and apply it to any tool it will still be visible in the Enchantment Block but not in the Enchanter, this I can only assume is another bug to fix.

**Comment by Cheaterpaul** [comment]
Fixed in EnchantmentMachine-1.17.1-1.0.6
