### ISSUE TITLE
Item is deleted if disenchanter is broken

### ISSUE THREAD

**Issue by nheath** [Cheaterpaul/EnchantmentMachine#13]
Hi,

Just wanted to report what appears like a bug I noticed when testing this mod. When using the disenchanter, and an item is in the output slot, if you break the disenchanter before removing the item, the disenchanter drops, but the item does not, and is not in the output slot when re-placed.

Minecraft: 1.18
Forge: 38.0.14
Mod: EnchantmentMachine-1.18-1.0.7-alpha+20211204-1727.jar

**Comment by Cheaterpaul** [comment]
thanks for reporting.

Will be fixed in the next version

**Comment by Cheaterpaul** [comment]
fixed by 8aba4eb5c96579d1e489848523c30fe196c4960b in 1.0.10
