### ISSUE TITLE
Version 1.18.1-1.0.9 enchantments disappearing from enchanter when I reload my world.

### ISSUE THREAD

**Issue by DSAH1997** [Cheaterpaul/EnchantmentMachine#14]
Each time I reopen my world all enchantments are gone from the enchanter

**Comment by DSAH1997** [comment]
I have to break each machine and replace it for it to work again as well.

**Comment by Cheaterpaul** [comment]
thanks for reporting,

seems like i have overseen that while testing the saving

**Comment by DSAH1997** [comment]
No worries, Thank you
