### ISSUE TITLE
Method save not found

### ISSUE THREAD

**Issue by emihead** [Cheaterpaul/EnchantmentMachine#16]
Minecraft 1.18.1
EnchantmentMachine-1.18.1-1.0.11
Forge 39.0.55

Crash report
[crash-2022-01-23_02.24.07-server.txt](https://github.com/Cheaterpaul/EnchantmentMachine/files/7920165/crash-2022-01-23_02.24.07-server.txt)

I got some help from a modder who told me that one of the tile entities had some trouble saving its contents, and that you should "use the saveAdditional function and not the save one" for 1.18.

**Comment by Cheaterpaul** [comment]
fixed in 1.0.12
