### ISSUE TITLE
Crash when attempting to join server

### ISSUE THREAD

**Issue by K4N0** [Cheaterpaul/EnchantmentMachine#17]
Can't join the server with this mod installed on both.
After the second attempt at login into the server I crash. 
https://pastebin.com/PgFLwGin

Server latest
[latest.log](https://github.com/Cheaterpaul/EnchantmentMachine/files/8424366/latest.log)
.

**Comment by Cheaterpaul** [comment]
This looks like it is caused by Enchantment Edit Table / DisenchantmentEditTable and not by this mod
