### ISSUE TITLE
Enchantment Machine Crashing when Style.getColor is null

### ISSUE THREAD

**Issue by Speiger** [Cheaterpaul/EnchantmentMachine#18]
https://github.com/TinyModularThings/UniqueEnchantments/issues/60

Moving this to you since you didn't look at minecrafts documentation.
(Last comment explains it)

**Comment by Cheaterpaul** [comment]
@AuroraHydroid check out the new 1.16.4-1.0.8 version

**Comment by Speiger** [comment]
That was quick and painless. Thanks

**Comment by AuroraHydroid** [comment]
Now the game crashes as soon as I click the enchanter. ;__;

https://pastebin.com/rx2CQrVt

**Comment by Cheaterpaul** [comment]
I overlooked the same error at a different place with the previous quickfix. Should now be fixed with 1.16.5-1.0.9
