### ISSUE TITLE
problem with multiple enchantments 

### ISSUE THREAD

**Issue by ElGomez23** [Cheaterpaul/EnchantmentMachine#23]
There is a problem when you have many enchantments stored in which when you hit the arrow on an enchantment it does not select the enchantment you have but instead takes one of the first enchantments

**Comment by Cheaterpaul** [comment]
What Minecraft and EnchantmentMachine versions are you using?

**Comment by ElGomez23** [comment]
we are using 1.19.3 and the mod is 1.1.0. Forge version 1.19.3-forge-44.1.0

**Comment by Cheaterpaul** [comment]
i uploaded a new version
