### ISSUE TITLE
I made a simplified Chinese json, and I hope it can be used in subsequent versions.

### ISSUE THREAD

**Issue by shenyx110** [Cheaterpaul/EnchantmentMachine#26]
我做了一个简体中文的语言文件，希望可以在后续版本支持

I made a simplified Chinese json, and I hope it can be used in subsequent versions.

{
  "block.enchantmentmachine.enchanter_block": "附魔机",
  "tile.enchantmentmachine.enchanter.name": "附魔机",
  "block.enchantmentmachine.disenchanter_block": "祛魔机",
  "tile.enchantmentmachine.disenchanter.name": "祛魔机",
  "block.enchantmentmachine.enchantment_block": "附魔方块",
  "itemGroup.enchantmentmachine": "附魔机器",
  "text.enchantmentmachine.enchant": "附魔",
  "text.enchantmentmachine.enchant_for_level": "附魔将要使用 %d 等级",
  "text.enchantmentmachine.require_level": "需要 %d 等级",
  "text.enchantmentmachine.unavailable": "有冲突的",
  "text.enchantment_block.contained_enchantments": "包含的附魔能量: %s",
  "text.enchantmentmachine.next_to_storage_block": "必须放置在 %s"
}

**Comment by Cheaterpaul** [comment]
Currently there already exists a simplified chinese translation. You can find it [on Crowdin](https://crowdin.com/project/enchantmentmachine/zh-CN). I included the translations that where missing, but i can not say whether your or the existing translations are better. If you want you can suggest your translation there.
