### ISSUE TITLE
1.20.1 enchanter dosnt enchant

### ISSUE THREAD

**Issue by hallool** [Cheaterpaul/EnchantmentMachine#27]
so im playing with modded enchants and vanilla the disenchanter disenchants modded enchants and the enchanter  gives them in my sword but it only works 1 time then i need to rejoin my single player world replace the enchanter to get another enchantment samt with vanille stuff help i activated aaal(cheat Mode) stuff in the config but i cant seem to find out how to edit /max enchantment levels) i hope this can fix my problem i used non enchanted weapons to  

Edit:   only the first button works the top one all below dont

**Comment by Cheaterpaul** [comment]
I am not sure if I follow.

1. So you have some enchantments disenchanted (e.g. sharpness II, Looting I and Mending)
2. You then put the sword in the enchanter
3. You select The first enchantment that is listed
4. Now you can no longer add enchantments to the sword
5. After destroying and playing a new enchanter you can enchant the sword further

Did I understand this correctly?
  

> Now you can no longer add enchantments to the sword

> Edit: only the first button works the top one all below dont

What indicates that you can no longer enchant the sword. Are the other enchantments red, does nothing happen when clicking the arrow?
Same for

**Comment by hallool** [comment]
no for example i put my item in and only the first slot button works i can use it how much i want but the other slots button dosnt work look at screenshot   
![grafik](https://github.com/Cheaterpaul/EnchantmentMachine/assets/48066058/4ec9efb1-2b23-4e82-98a3-800ee94714ee)

the red works no matter how much i use it

 the black and all below dont work they only work if i reaload my world and replace it for 1 use..

**Comment by hallool** [comment]
so i can enchant but only in the first slot so if i want like the potato enchant i need to get piercing on the book   so i can use the potato enchant in screenshot hope u understand Xd

**Comment by Moses24713** [comment]
Enchanter is also not working for me anymore, or does work 5% of the time

**Comment by NekoAutomata** [comment]
This is still a major issue. Even vanilla enchants can't be applied. Clean item or not.

**Comment by KalCorp** [comment]
Same Issue.   Sometimes i can get it to work and others i cant.

**Comment by artjt1** [comment]
Same issue, except, when you have a lot of enchants and the window with the list is full, you can only select from the first page. As soon as you scroll down the next enchant that is not shown on the first window and all below do not work. 

The arrow is green, red or brown, but not selectable. scroll to the top and they work.

Also, the output on the disenchanter, when you us a book, is an enchanted book, not a book. 

When I am in creative game mode all works as expected, in survival it does not.

I had this issue with:
Minecraft 1.20.1
Forge 47.2.5
 Java 17.0.9.0

mod list 
Bookshelf
Enchantment Descriptions
Enchantment Machine
Just Enough Items(JEI)

**Comment by Cheaterpaul** [comment]
fixed in the newest version
