### ISSUE TITLE
[Bug] Enchanter do not recognize sufficient level

### ISSUE THREAD

**Issue by LuciusV** [Cheaterpaul/EnchantmentMachine#4]
Enthanter says that I need 2 levels to enchant, I have 2 levels ,and still I can't enchant
![2021-03-18_21 09 06](https://user-images.githubusercontent.com/11925386/111631435-591edc80-882e-11eb-89bd-64cb2e3955ca.png)

**Comment by maxanier** [comment]
Oh, thx for reporting, will be fixed.
Apparently you always need an additional level at the moment
