### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Andrey-007** [Cheaterpaul/EnchantmentMachine#9]
Minecraft: 1.16.5
Forge: 36.1.0
Mods: jei-1.16.5-7.7.0.107, EnchantmentMachine-1.16.4-1.0.3, Quark-r2.4-314, AutoRegLib-1.6-49
description:
Ancient tomes from the quark mod duplicates enchantments
https://quarkmod.net/#features --> Tools

Photo:
![2021-07-09_11 55 58](https://user-images.githubusercontent.com/17749204/125052557-c5a73b00-e0ac-11eb-9652-85a43c4f6b80.png)
![2021-07-09_11 56 08](https://user-images.githubusercontent.com/17749204/125052567-c9d35880-e0ac-11eb-910b-b3409bbd97e0.png)
![2021-07-09_11 56 20](https://user-images.githubusercontent.com/17749204/125052574-cb048580-e0ac-11eb-90b8-6a3509e04dbf.png)
![2021-07-09_11 56 23](https://user-images.githubusercontent.com/17749204/125052578-cc35b280-e0ac-11eb-94e5-633efcb11a02.png)
![2021-07-09_11 56 28](https://user-images.githubusercontent.com/17749204/125052579-cd66df80-e0ac-11eb-9b85-7c85f948a42f.png)
![2021-07-09_11 56 33](https://user-images.githubusercontent.com/17749204/125052584-cdff7600-e0ac-11eb-9725-6de22ca18f3c.png)

**Comment by Cheaterpaul** [comment]
Thanks for reporting, this issue should be fixed with version 1.0.4 as well as probably other similar items
